# version: "2"
services:



  # dotnet_client:
  #   build:
  #     context: client/GisaxsClient
  #     dockerfile: GisaxsClient/Dockerfile
  #   command: tail -f /dev/null
  #   links:
  #     - redis_jobs
  #   ports:
  #     - "8080:80"
  #     - "8081:443"

  redis_jobs:
    image: redis:latest
    ports:
      - 6379:6379
  pg_admin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"

  postgres_users:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  # gisaxs_backend:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile.cuda
  #   ports:
  #     - '5555:5555'
  #   # networks:
  #   #   - aspnetcoreapp-network
  #   cap_add:
  #     - SYS_PTRACE
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [ gpu ]
  # gisaxs_remote_dev:
  #   build: backend
  #   entrypoint: /docker-entrypoint.sh
  #   image: cuda_dev:latest
  #   container_name: gisaxs_remote_dev
  #   command: tail -f /dev/null
  #   ports:
  #     - '5555:5555'
  #     - '2222:22'
  #   cap_add:
  #     - SYS_PTRACE
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
volumes:
  db:
    driver: local

networks:
  aspnetcoreapp-network:
    driver: bridge
