# version: "2"
services:
  #  device:
  #    build: .
  #    ports: [ 5558:5558, 5559:5559, 5556:5556, 5557:5557 ]
  #    deploy:
  #      resources:
  #        reservations:
  #          devices:
  #            - capabilities: [ gpu ]
  redis_jobs:
    #  image: redislabs/rejson:latest
    image: redis:latest
    #  command: --port 6380 --appendonly no --save ""
    networks:
      - aspnetcoreapp-network
    ports:
      - 6379:6379

  dotnet_client:
    build:
      context: client/GisaxsClient/GisaxsClient
      # dockerfile: Dockerfile
    command: tail -f /dev/null
    links:
      - redis_jobs
    #   - postgres_users
    #   - gisaxs_backend
    networks:
      - aspnetcoreapp-network
    ports:
      - "8080:80"
      - "8081:443"
  pg_admin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"

  postgres_users:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base
    #  networks:
    #     - aspnetcoreapp-network
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      # - ./postgres-scripts:/docker-entrypoint-initdb.d
  gisaxs_backend:
    build: backend
    ports:
      - '5555:5555'
    networks:
      - aspnetcoreapp-network
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  # gisaxs_remote_dev:
  #   build: backend
  #   entrypoint: /docker-entrypoint.sh
  #   image: cuda_dev:latest
  #   container_name: gisaxs_remote_dev
  #   command: tail -f /dev/null
  #   ports:
  #     - '5555:5555'
  #     - '2222:22'
  #   cap_add:
  #     - SYS_PTRACE
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
volumes:
  db:
    driver: local

networks:
  aspnetcoreapp-network:
    driver: bridge
