# version: "2"
services:
#  device:
#    build: .
#    ports: [ 5558:5558, 5559:5559, 5556:5556, 5557:5557 ]
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [ gpu ]
  redis_jobs:
   image: redislabs/rejson:latest
   command: --port 6380 --appendonly no --save ""
   ports: 
    - 6380:6380

  pg_admin4:
    image: dpage/pgadmin4:latest 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  postgres_users:
   image: postgres:latest
   restart: always
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base
  #  command: [sh, -c, cd docker-entrypoint-initdb.d && chmod +x init-scatterstore.sh]
   ports:
    - '5432:5432'
   volumes: 
    - db:/var/lib/postgresql/data
    # - ./postgres-scripts:/docker-entrypoint-initdb.d
  gisaxs_remote_dev:
    build: .
    entrypoint: /docker-entrypoint.sh
    image: cuda_dev:latest
    container_name: gisaxs_remote_dev
    command: tail -f /dev/null
    ports:
      - '5555:5555'
      - '2222:22'
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  db:
    driver: local
  # redis_clients:
  #   image: redislabs/rejson:latest
  #   command: --port 6380
  #   command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
  #   ports: [6380:6380]

  #   command: bash -c "cd source && ./build.sh && ./build/apps/ModelSimulator/ModelSimulator"
  #   volumes:
  #       - C:/temp/source:/source