using Dapper;
using Microsoft.Extensions.Configuration;
using Npgsql;
using ScatterStore.Controllers;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

#nullable enable

namespace ScatterStore
{
    public class ImageStore
    {
        private readonly string connectionString;
        public ImageStore(IConfiguration configuration, string connectionId = "Default")
        {
            connectionString = configuration.GetConnectionString(connectionId);
            using IDbConnection connection = new NpgsqlConnection(connectionString);
            connection.Execute(
                @$"CREATE TABLE IF NOT EXISTS images (
                    Id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    Name VARCHAR(50) NOT NULL,
                    Size BIGINT NOT NULL,
                    Data double precision[] NOT NULL); "
                );
        }

        public async Task<IEnumerable<ImageInfo>> Get()
        {
            using IDbConnection connection = new NpgsqlConnection(connectionString);
            return await connection.QueryAsync<ImageInfo>(@"SELECT Id, Name, Size FROM images");
        }

        public async Task<IEnumerable<Image>> Get(long id)
        {
            using IDbConnection connection = new NpgsqlConnection(connectionString);
            return await connection.QueryAsync<Image>(@$"SELECT * FROM images WHERE Id = {id}");
        }

        public async void Delete(long id)
        {
            using IDbConnection connection = new NpgsqlConnection(connectionString);
            await connection.ExecuteAsync($@"DELETE * FROM images WHERE Id = {id}");
        }

        public async void Insert(Image image)
        {
            using IDbConnection connection = new NpgsqlConnection(connectionString);
            await connection.ExecuteAsync($@"
                    INSERT INTO images (name, size, data)
                    VALUES (@name, @size, @data)", new { name = image.Info.Name, size = image.Info.Size, data = image.Data });
        }

        public async void Insert(IReadOnlyCollection<Image> images)
        {
            using IDbConnection connection = new NpgsqlConnection(connectionString);
            using IDbTransaction transaction = connection.BeginTransaction();
            foreach (var image in images)
            {
                await connection.ExecuteAsync($@"
                        INSERT INTO users (id, name, size, data)
                        VALUES (@name, @size, @data)", new { name = image.Info.Name, size = image.Info.Size, data = image.Data }, transaction);
            }
            transaction.Commit();
        }
    }
}
