apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: private-registry-docker-registry
  namespace: default
spec:
  weighted:
    services:
      - name: private-registry-docker-registry
        port: 5000
