name: Gisaxs Client Image Ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Test
        run: echo ${{ steps.semantic.outputs.new_release_version }}
      - name: Build and push client docker image
        uses: docker/build-push-action@v3
        with:
          context: ./client/GisaxsClient
          file: client/GisaxsClient/GisaxsClient/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/client:latest, ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/client:${{ steps.version-bump.outputs.newTag }}
      #- name: Build and push backend docker image
     #   uses: docker/build-push-action@v3
      #  with:
      #    context: ./backend
     #     push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/backend:latest, ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/backend:${{ steps.version-bump.outputs.newTag }}
