name: Gisaxs Client Image Ci

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish:
    env:
      VERSION: "${github.ref_name:1}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Print image-tag
        run: echo "${github.ref_name:1}"

      - name: Build and push client docker image
        uses: docker/build-push-action@v3
        with:
          context: ./client/GisaxsClient
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/client:latest, ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/client:$VERSION
          
      - name: Build and push backend docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile.alpine
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/backend:latest, ${{secrets.REGISTRY}}/${{secrets.REPO_NAME}}/backend:$VERSION
